#!/usr/bin/python3

def factorise(num):
    if (num % 2) == 0:
        print("{:.0f}={:.0f}*2".format(num, num / 2))
    else:
        i = 3
        while num % i != 0:
            i += 2
        print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))
import sys
with open(sys.argv[1], "r") as file:
    data = file.readlines()
    for line in data:
        number = int(line)
        factorise(number)
